# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches: main
    
name: knit

jobs:
  knit:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    
    steps:
      - uses: actions/checkout@v3
    
      - uses: r-lib/actions/setup-pandoc@v2
    
      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-tinytex@v2 
          
      - name: Install dependencies
        run: |
          install.packages(c('ggplot2','rmarkdown','knitr','remotes','tidyverse','data.table','lubridate','maps','ggpubr','ggmap','grid','gtable','magick','tinytex'))
          load("MONTHLY_REPORT_DATA.RData")

        shell: Rscript {0}
        
      - name: Render my document to all types
        run: Rscript -e 'rmarkdown::render("AutomatedMonthlyReport_G68.Rmd", output_format = "all")'
            
      - name: Commit results
        run: |
          git add output/AutomatedMonthlyReport_G68*
          git commit -m 'Latest report produced' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
  
